"""Initial56 Migration

Revision ID: 2a12fd463e89
Revises: 4035134eab3c
Create Date: 2019-03-07 10:38:35.308542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a12fd463e89'
down_revision = '4035134eab3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agronomist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_diseases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symptoms', sa.String(), nullable=True),
    sa.Column('agronomist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agronomist_id'], ['agronomist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('diseases', sa.Column('agronomist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'diseases', 'agronomist', ['agronomist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'diseases', type_='foreignkey')
    op.drop_column('diseases', 'agronomist_id')
    op.drop_table('user_diseases')
    op.drop_table('agronomist')
    # ### end Alembic commands ###
