"""Initial34 Migration

Revision ID: 4035134eab3c
Revises: 5918479af966
Create Date: 2019-03-07 09:45:14.265555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4035134eab3c'
down_revision = '5918479af966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diseases', sa.Column('control', sa.String(), nullable=True))
    op.drop_column('diseases', 'Control')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diseases', sa.Column('Control', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('diseases', 'control')
    # ### end Alembic commands ###
