"""Initial12 Migration

Revision ID: 5918479af966
Revises: 
Create Date: 2019-03-07 09:18:16.635817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5918479af966'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diseases', sa.Column('Control', sa.String(), nullable=True))
    op.add_column('diseases', sa.Column('category', sa.String(), nullable=True))
    op.add_column('diseases', sa.Column('name', sa.String(), nullable=True))
    op.add_column('diseases', sa.Column('symptoms', sa.String(), nullable=True))
    op.drop_column('diseases', 'title')
    op.drop_column('diseases', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diseases', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('diseases', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('diseases', 'symptoms')
    op.drop_column('diseases', 'name')
    op.drop_column('diseases', 'category')
    op.drop_column('diseases', 'Control')
    # ### end Alembic commands ###
