"""Initial Migration3

Revision ID: 9e2723216ac0
Revises: 63729c38ce56
Create Date: 2019-03-08 09:43:27.974194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e2723216ac0'
down_revision = '63729c38ce56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diseases', sa.Column('approved', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diseases', 'approved')
    # ### end Alembic commands ###
